version: "3"
services:
  db:
    image: "postgres:11"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reportserver
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./reportserver-ui
    ports:
      - "8081:80"